Gestion\ContactBundle\Entity\Contact:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        pays:
            type: string
            length: 255
        ville:
            type: string
            length: 255
        phone:
            type: string
            length: 255
    lifecycleCallbacks: {  }
